**1)** Se va a importar la librería *numpy* y la va a llamar *np*

Una librería es un conjunto de herramientas ya programadas para no tener que programar desde cero.

*numpy* permite trabajar con:
- MATEMÁTICAS AVANZADAS

- ARRAYS

Ejemplo:

[1, 2, 3]

- MATRICES

Ejemplo:

[[1, 2]

[3, 4]]

In [ ]:
#1
import numpy as np

**2)** Se va a importar el submodulo *pyplot* de la librería *matplotlib* y la va a llamar *plt*. Para importar este submodulo se debe escribir como *matplotlib.pyplot*

Se usa el submodulo, porque la librería no tiene las funciones directas para hacer gráficos.

Ejemplo:

- MATPLOTLIB = Carro

- PYPLOT = La radio del carro (Se lo utiliza para escuchar música)

In [ ]:
#2
import matplotlib.pyplot as plt

**3)** Se va a importar la clase *LocalOutlierFactor* del submodulo *neighbors* de la librería *scikit-learn (sklearn)*.

- La libería *sklearn* sirve para: Clasificación, Regresión, Clustering, etc..
- El submodulo *neighbors* tiene algoritmos para "veninos mas cercanos": NearestNeighbors, LocalOutliersFactor, etc...
- La clase *LocalOutliersFactor* es un algoritmo para detectar outliers.

In [8]:
#3
from sklearn.neighbors import LocalOutlierFactor

**4)** Se va a fijar números aleatorios, es decir que no van a cambiar.

Usando el submodulo *random* de la librería *numpy (np)*, devuelve un número aleatorio difernte cada vez.

Usando *random.seed(#Algun numero)* de la librería *numpy (np)*, devuelve el mismo número aleatorio siempre.

In [ ]:
#4
np.random.seed(42)

0.3745401188473625


np.random.randn(100,2) Es un generador de números aleatorios que siguen una distribución normal (también llamada campana de Gauss).
genera 100 filas
cada una de las filas con 2 números
los números siguen una distribución normal con media 0 y desviación estándar 1
¿Por qué hacemos 0.3 * ...? Porque queremos que los puntos estén más juntos y centrados.
Multiplicar los valores aleatorios por 0.3:
reduce su tamaño

hace que el grupo de puntos sea más compacto

evita que se dispersen demasiado en el gráfico
Antes una fila: [-1.2 0.7] Después de multiplicar x 0.3: [-0.36 0.21]. Mucho más cerca del origen.
¿Qué significa X_inliers = ...? Estamos guardando los resultados en una variable llamada X_inliers.
El nombre viene de:
inlier → punto normal, punto dentro del grupo

lo contrario de outlier, que es un punto raro o externo
X_inliers es un grupo de 100 puntos normales, cada uno con 2 coordenadas (x, y).
Estos serán los datos “buenos” o “normales” del dataset.

In [ ]:
np.random.randn(100, 2)

array([[ 0.35778736,  0.56078453],
       [ 1.08305124,  1.05380205],
       [-1.37766937, -0.93782504],
       [ 0.51503527,  0.51378595],
       [ 0.51504769,  3.85273149],
       [ 0.57089051,  1.13556564],
       [ 0.95400176,  0.65139125],
       [-0.31526924,  0.75896922],
       [-0.77282521, -0.23681861],
       [-0.48536355,  0.08187414],
       [ 2.31465857, -1.86726519],
       [ 0.68626019, -1.61271587],
       [-0.47193187,  1.0889506 ],
       [ 0.06428002, -1.07774478],
       [-0.71530371,  0.67959775],
       [-0.73036663,  0.21645859],
       [ 0.04557184, -0.65160035],
       [ 2.14394409,  0.63391902],
       [-2.02514259,  0.18645431],
       [-0.66178646,  0.85243333],
       [-0.79252074, -0.11473644],
       [ 0.50498728,  0.86575519],
       [-1.20029641, -0.33450124],
       [-0.47494531, -0.65332923],
       [ 1.76545424,  0.40498171],
       [-1.26088395,  0.91786195],
       [ 2.1221562 ,  1.03246526],
       [-1.51936997, -0.48423407],
       [ 1.26691115,

In [ ]:
X_inliers = 0.3 * np.random.randn(100, 2)

In [ ]:
X_inliers

array([[ 0.14901425, -0.04147929],
       [ 0.19430656,  0.45690896],
       [-0.07024601, -0.07024109],
       [ 0.47376384,  0.23023042],
       [-0.14084232,  0.16276801],
       [-0.13902531, -0.13971893],
       [ 0.07258868, -0.57398407],
       [-0.51747535, -0.16868626],
       [-0.30384934,  0.0942742 ],
       [-0.27240722, -0.42369111],
       [ 0.43969463, -0.06773289],
       [ 0.02025846, -0.42742446],
       [-0.16331482,  0.03327678],
       [-0.34529807,  0.11270941],
       [-0.18019161, -0.08750812],
       [-0.18051198,  0.55568346],
       [-0.00404917, -0.31731328],
       [ 0.24676347, -0.36625309],
       [ 0.06265908, -0.58790104],
       [-0.39845581,  0.05905837],
       [ 0.22153997,  0.05141048],
       [-0.03469448, -0.09033111],
       [-0.4435566 , -0.21595326],
       [-0.13819163,  0.31713667],
       [ 0.10308549, -0.52891205],
       [ 0.09722519, -0.11552468],
       [-0.2030766 ,  0.18350289],
       [ 0.30929986,  0.27938404],
       [-0.25176526,

Qué es X_inliers + 2?
A cada punto del arreglo, súmale 2 a las dos coordenadas:
Si un punto era: [-0.36, 0.21]. Entonces [-0.36 + 2, 0.21 + 2] = [1.64, 2.21]
PREGUNTA AL CURSO: ¿Qué es X_inliers - 2?
RESPUESTA: ¿Qué es X_inliers - 2? [-0.36, 0.21] → [-2.36, -1.79]
¿Qué hace np.r_[ ... , ... ]?
Es una función que une dos conjuntos de datos verticalmente.
Así: [ grupo desplazado +2 ] [ grupo desplazado -2 ] Resultado: una sola matriz con 200 filas.
¿Por qué hacemos esto?
Generamos dos grupos de puntos “buenos”:
uno centrado alrededor de (2,2)
otro centrado alrededor de (-2,-2)
Estos dos grupos representarán datos normales.

In [ ]:
X_inliers = np.r_[X_inliers + 2, X_inliers - 2]

In [ ]:
X_inliers

array([[ 2.14901425,  1.95852071],
       [ 2.19430656,  2.45690896],
       [ 1.92975399,  1.92975891],
       [ 2.47376384,  2.23023042],
       [ 1.85915768,  2.16276801],
       [ 1.86097469,  1.86028107],
       [ 2.07258868,  1.42601593],
       [ 1.48252465,  1.83131374],
       [ 1.69615066,  2.0942742 ],
       [ 1.72759278,  1.57630889],
       [ 2.43969463,  1.93226711],
       [ 2.02025846,  1.57257554],
       [ 1.83668518,  2.03327678],
       [ 1.65470193,  2.11270941],
       [ 1.81980839,  1.91249188],
       [ 1.81948802,  2.55568346],
       [ 1.99595083,  1.68268672],
       [ 2.24676347,  1.63374691],
       [ 2.06265908,  1.41209896],
       [ 1.60154419,  2.05905837],
       [ 2.22153997,  2.05141048],
       [ 1.96530552,  1.90966889],
       [ 1.5564434 ,  1.78404674],
       [ 1.86180837,  2.31713667],
       [ 2.10308549,  1.47108795],
       [ 2.09722519,  1.88447532],
       [ 1.7969234 ,  2.18350289],
       [ 2.30929986,  2.27938404],
       [ 1.74823474,

¿Qué es np.random.uniform()?
Es un generador de números aleatorios que elige valores entre dos límites:
low=-4 significa el valor mínimo posible es −4
high=4 significa el valor máximo posible es 4
Es como decir:
“Elige números entre −4 y 4”.
¿Qué significa size=(20, 2)?
Vamos a generar 20 puntos, donde cada punto tiene 2 coordenadas (x, y)
Entonces crea una matriz así:
[ [valor, valor], [valor, valor], ... 20 veces ]
¿Por qué estos son outliers?
Porque estos puntos pueden caer en cualquier parte del cuadrado: x entre −4 y 4 y entre −4 y 4
Esto incluye puntos:
Lejos de los grupos normales

Totalmente dispersos

Con ubicaciones aleatorias
Son perfectos para representar “valores raros”.

In [ ]:
#Generamos algunos outliers
X_outliers = np.random.uniform(low=-4, high=4, size=(20, 2))

In [ ]:
X_outliers

array([[ 3.01898458,  1.92614894],
       [ 1.57612593,  1.61987267],
       [-1.12407079, -1.65126525],
       [ 2.47488924,  2.48090716],
       [ 2.93657855,  3.30592442],
       [ 0.09073919,  0.01213036],
       [ 2.38636143,  1.19971145],
       [ 1.61573502,  2.36634136],
       [ 3.12004273, -1.29603875],
       [-0.99533638, -3.24814448],
       [ 0.62624113, -3.71246181],
       [-0.27521585,  0.34115708],
       [-1.70766998,  0.72666608],
       [-3.755998  , -3.70121449],
       [ 2.58080449, -1.11847487],
       [-2.9835159 ,  0.17794608],
       [ 2.15994842, -2.27343178],
       [ 0.98312381, -3.31722028],
       [-3.58654623,  0.25083705],
       [ 0.32508097,  1.09943921]])

Une las matrices inliners y outliners

In [ ]:
X = np.r_[X_inliers, X_outliers]

In [ ]:
X

array([[ 2.14901425,  1.95852071],
       [ 2.19430656,  2.45690896],
       [ 1.92975399,  1.92975891],
       [ 2.47376384,  2.23023042],
       [ 1.85915768,  2.16276801],
       [ 1.86097469,  1.86028107],
       [ 2.07258868,  1.42601593],
       [ 1.48252465,  1.83131374],
       [ 1.69615066,  2.0942742 ],
       [ 1.72759278,  1.57630889],
       [ 2.43969463,  1.93226711],
       [ 2.02025846,  1.57257554],
       [ 1.83668518,  2.03327678],
       [ 1.65470193,  2.11270941],
       [ 1.81980839,  1.91249188],
       [ 1.81948802,  2.55568346],
       [ 1.99595083,  1.68268672],
       [ 2.24676347,  1.63374691],
       [ 2.06265908,  1.41209896],
       [ 1.60154419,  2.05905837],
       [ 2.22153997,  2.05141048],
       [ 1.96530552,  1.90966889],
       [ 1.5564434 ,  1.78404674],
       [ 1.86180837,  2.31713667],
       [ 2.10308549,  1.47108795],
       [ 2.09722519,  1.88447532],
       [ 1.7969234 ,  2.18350289],
       [ 2.30929986,  2.27938404],
       [ 1.74823474,

len(X) → cuenta todos los puntos (inliers + outliers).
200 inliers
20 outliers
total = 220
np.ones(...) → crea un arreglo lleno de unos. [1, 1, 1, 1, 1, 1, ...]
dtype=int → asegura que sean números enteros.
POR QUÉ LO HACEMOS?
Estamos creando un arreglo que dice:
1 = punto normal (inlier)
−1 = punto raro (outlier)
Por ahora marcamos todos como normales, pero en la siguiente línea corregiremos eso.

In [ ]:
n_outliers = len(X_outliers)

Visualizo el valor de la variable

In [ ]:
n_outliers

20

Es el modelo real
len(X) → cuenta todos los puntos (inliers + outliers).
200 inliers
20 outliers
total = 220
np.ones(...) → crea un arreglo lleno de unos. [1, 1, 1, 1, 1, 1, ...]
dtype=int → asegura que sean números enteros.
POR QUÉ LO HACEMOS?
Estamos creando un arreglo que dice:
1 = punto normal (inlier)
−1 = punto raro (outlier)
Por ahora marcamos todos como normales, pero en la siguiente línea corregiremos eso.

In [ ]:
ground_truth = np.ones(len(X), dtype=int)


In [ ]:
ground_truth

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

ground_truth es una lista de 1s: [1, 1, 1, 1, ... 1]
-n_outliers: significa: “las últimas n_outliers posiciones”, o sea, los últimos 20 elementos
Si hay 220 datos: tomamos los elementos 200 al 219 y les ponemos −1

In [ ]:
ground_truth[-n_outliers:] = -1

In [ ]:
ground_truth[-n_outliers:]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1])

In [ ]:
#Aquí vamos a entrenar el modelo para detectar puntos raros
clf = LocalOutlierFactor(n_neighbors=20, contamination=0.1)

In [ ]:
clf

LocalOutlierFactor(contamination=0.1)

Usaremos fit_predict para obtener las etiquetas (normal o outlier).
LOF no permite predecir sobre datos nuevos cuando se usa como detector de outliers.
LOF estudia densidades locales del conjunto completo
Si le damos un nuevo punto, no sabe dónde encajarlo
Para eso existe un modo especial llamado novelty=True (pero aquí no lo usaremos)

In [ ]:
y_pred = clf.fit_predict(X)

In [ ]:
y_pred

array([ 1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1