**1)** Se va a importar la librería *numpy* y la va a llamar *np*

Una librería es un conjunto de herramientas ya programadas para no tener que programar desde cero.

*numpy* permite trabajar con:
- MATEMÁTICAS AVANZADAS

- ARRAYS

Ejemplo:

[1, 2, 3]

- MATRICES

Ejemplo:

[[1, 2]

[3, 4]]

In [ ]:
#1
import numpy as np

**2)** Se va a importar el submodulo *pyplot* de la librería *matplotlib* y la va a llamar *plt*. Para importar este submodulo se debe escribir como *matplotlib.pyplot*

Se usa el submodulo, porque la librería no tiene las funciones directas para hacer gráficos.

Ejemplo:

- MATPLOTLIB = Carro

- PYPLOT = La radio del carro (Se lo utiliza para escuchar música)

In [ ]:
#2
import matplotlib.pyplot as plt

**3)** Se va a importar la clase *LocalOutlierFactor* del submodulo *neighbors* de la librería *scikit-learn (sklearn)*.

- La libería *sklearn* sirve para: Clasificación, Regresión, Clustering, etc..
- El submodulo *neighbors* tiene algoritmos para "veninos mas cercanos": NearestNeighbors, LocalOutliersFactor, etc...
- La clase *LocalOutliersFactor* es un algoritmo para detectar outliers.

In [ ]:
#3
from sklearn.neighbors import LocalOutlierFactor

**4)** Se va a fijar números aleatorios, es decir que no van a cambiar.

Usando el submodulo *random* de la librería *numpy (np)*, devuelve un número aleatorio diferente cada vez.

Usando *random.seed(#Algun numero)* de la librería *numpy (np)*, devuelve el mismo número aleatorio siempre.

NOTA: El número en *random.seed* es solo el valor que se tomara de base para calcular la misma aleatoriedad de los datos.

In [ ]:
#4
np.random.seed(42)

**5)** Se va a generar una matriz de (N° Filas, N° Columnas) con números aleatorios (previamente fijos con seed(42)).

- Si se usa *np.random.rand* va a solicitar números aleatorios entre 0 y 1

- Si se usa *np.random.randn* va a solicitar números aleatorios que siguen una distribución normal (Campana de Gauss)

In [ ]:
#5
np.random.randn(100, 2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ],
       [ 0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259],
       [-1.15099358,  0.37569802],
       [-0.60063869, -0.29169375],
       [-0.60170661,  1.85227818],
       [-0.01349722, -1.05771093],
       [ 0.82254491, -1.22084365],
       [ 0.2088636 , -1.95967012],
       [-1.32818605,  0.19686124],
       [ 0.73846658,  0.17136828],
       [-0.11564828, -0.3011037 ],
       [-1.47852199, -0.71984421],
       [-0.46063877,  1.05712223],
       [ 0.34361829, -1.76304016],
       [ 0.32408397, -0.38508228],
       [-0.676922  ,  0.61167629],
       [ 1.03099952,  0.93128012],
       [-0.83921752,

**6)** Se va a generar una matriz llamada *X_inliers* multiplicada por 0.3 a partir de la matriz generada con np.random.randn(#Fila, #Col).

Esta nueva matriz, tiene las mismas dimesiones que la matriz de origen.

In [ ]:
#6
X_inliers = 0.3 * np.random.randn(100, 2)

X_inliers

array([[ 0.10733621,  0.16823536],
       [ 0.32491537,  0.31614062],
       [-0.41330081, -0.28134751],
       [ 0.15451058,  0.15413579],
       [ 0.15451431,  1.15581945],
       [ 0.17126715,  0.34066969],
       [ 0.28620053,  0.19541738],
       [-0.09458077,  0.22769077],
       [-0.23184756, -0.07104558],
       [-0.14560906,  0.02456224],
       [ 0.69439757, -0.56017956],
       [ 0.20587806, -0.48381476],
       [-0.14157956,  0.32668518],
       [ 0.01928401, -0.32332343],
       [-0.21459111,  0.20387932],
       [-0.21910999,  0.06493758],
       [ 0.01367155, -0.1954801 ],
       [ 0.64318323,  0.19017571],
       [-0.60754278,  0.05593629],
       [-0.19853594,  0.25573   ],
       [-0.23775622, -0.03442093],
       [ 0.15149618,  0.25972656],
       [-0.36008892, -0.10035037],
       [-0.14248359, -0.19599877],
       [ 0.52963627,  0.12149451],
       [-0.37826519,  0.27535858],
       [ 0.63664686,  0.30973958],
       [-0.45581099, -0.14527022],
       [ 0.38007334,

**7)** Se va a modificar la matriz *X_inliers*.
- Se van a tomar los valores originales de la matriz, y se los va a sumar 2 (+2).
- Se van a tomar los valores originales de la metriz, y se los va a restar 2 (-2).

- Los valores sumados y restados se los va a unir en la matriz, teniendo el doble de datos.

In [ ]:
#7
X_inliers = np.r_[X_inliers + 2, X_inliers - 2]

X_inliers

array([[ 2.10733621,  2.16823536],
       [ 2.32491537,  2.31614062],
       [ 1.58669919,  1.71865249],
       [ 2.15451058,  2.15413579],
       [ 2.15451431,  3.15581945],
       [ 2.17126715,  2.34066969],
       [ 2.28620053,  2.19541738],
       [ 1.90541923,  2.22769077],
       [ 1.76815244,  1.92895442],
       [ 1.85439094,  2.02456224],
       [ 2.69439757,  1.43982044],
       [ 2.20587806,  1.51618524],
       [ 1.85842044,  2.32668518],
       [ 2.01928401,  1.67667657],
       [ 1.78540889,  2.20387932],
       [ 1.78089001,  2.06493758],
       [ 2.01367155,  1.8045199 ],
       [ 2.64318323,  2.19017571],
       [ 1.39245722,  2.05593629],
       [ 1.80146406,  2.25573   ],
       [ 1.76224378,  1.96557907],
       [ 2.15149618,  2.25972656],
       [ 1.63991108,  1.89964963],
       [ 1.85751641,  1.80400123],
       [ 2.52963627,  2.12149451],
       [ 1.62173481,  2.27535858],
       [ 2.63664686,  2.30973958],
       [ 1.54418901,  1.85472978],
       [ 2.38007334,

**8)** Se va a generar una matriz de (N° Filas, N° Columnas) con números aleatorios (previamente fijos con seed(42)).

- Si se usa *np.random.rand* va a solicitar números aleatorios entre 0 y 1

- Si se usa *np.random.randn* va a solicitar números aleatorios que siguen una distribución normal (Campana de Gauss)

- Si se usa *np.random.uniform* va a solicitar números aleatorios entre un valor mínimo (low) y máximo (high)

In [ ]:
#8
X_outliers = np.random.uniform(low=-4, high=4, size=(20, 2))

X_outliers

array([[-0.68144398, -1.81274342],
       [-3.54899603,  2.91777901],
       [ 2.50320807,  3.99774139],
       [ 3.9730947 ,  0.44345364],
       [ 2.15189932,  3.55812584],
       [ 2.79717913, -2.02121519],
       [-0.39564692, -2.96672468],
       [ 3.63240822,  0.84939708],
       [-2.17085756,  1.37360548],
       [ 0.94502592, -1.13469826],
       [-3.09153926,  1.37258556],
       [ 0.16246161,  2.17854713],
       [ 0.16130801,  2.817452  ],
       [ 0.41525471,  0.48750377],
       [ 3.01322882, -0.77213707],
       [-2.92787817, -3.76973859],
       [ 2.04109805,  0.96247641],
       [ 1.63263814, -2.29628671],
       [-2.9090282 , -3.88364267],
       [-1.19529953,  0.71934149]])

**9)** Se va a unir la matriz *X_inliers* y bajo esta la *X_outliers*

- *X_inliers* con *X_outliers* se van a almacenar en la variable *X*

In [ ]:
#9
X = np.r_[X_inliers, X_outliers]

X

array([[ 2.10733621,  2.16823536],
       [ 2.32491537,  2.31614062],
       [ 1.58669919,  1.71865249],
       [ 2.15451058,  2.15413579],
       [ 2.15451431,  3.15581945],
       [ 2.17126715,  2.34066969],
       [ 2.28620053,  2.19541738],
       [ 1.90541923,  2.22769077],
       [ 1.76815244,  1.92895442],
       [ 1.85439094,  2.02456224],
       [ 2.69439757,  1.43982044],
       [ 2.20587806,  1.51618524],
       [ 1.85842044,  2.32668518],
       [ 2.01928401,  1.67667657],
       [ 1.78540889,  2.20387932],
       [ 1.78089001,  2.06493758],
       [ 2.01367155,  1.8045199 ],
       [ 2.64318323,  2.19017571],
       [ 1.39245722,  2.05593629],
       [ 1.80146406,  2.25573   ],
       [ 1.76224378,  1.96557907],
       [ 2.15149618,  2.25972656],
       [ 1.63991108,  1.89964963],
       [ 1.85751641,  1.80400123],
       [ 2.52963627,  2.12149451],
       [ 1.62173481,  2.27535858],
       [ 2.63664686,  2.30973958],
       [ 1.54418901,  1.85472978],
       [ 2.38007334,

**10)** Se va a contabilizar la cantidad de puntos (Filas) de la variable *X*, ese valor lo guardara en la variable *n*

In [ ]:
#10
n = len(X)

n

220

**11)** Se va a contabilizar la cantidad de puntos (Filas) de la variable *X_inliers*, ese valor lo guardara en la variable *n_inliers*

In [ ]:
#11
n_inliers = len(X_inliers)

n_inliers

200

**12)** Se va a contabilizar la cantidad de puntos (Filas) de la variable *X_outliers*, ese valor lo guardara en la variable *n_outliers*

In [ ]:
#12
n_outliers = len(X_outliers)

n_outliers

20

**13)** Se va a crear un array *ground_truth* con la cantidad de puntos que haya en la matriz *x*

-Usando el submodulo *np.ones* de la librería *numpy (np)*, va a llenar los datos con el número 1.

NOTA: Estamos haciendo que todos nuestros datos sean 1.

In [ ]:
#13
ground_truth = np.ones(len(X), dtype=int)

ground_truth


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**14)** Se va a modificar el array *ground_truth* colocando a la CANTIDAD de la variable *n_outliers* un valor de *-1*

In [ ]:
#14
ground_truth[-n_outliers:] = -1

ground_truth

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

**15)** Se va a utilizar la clase (algoritmo) *LocalOutlierFactor* del submodulo *neighbors* de la libería *sklearn* y se lo va a almacenar en la variable *clf*

- n_neighbors=#Número: Para cada punto evalua sus #Número vecinos más cercanos
- contamination=#Número: Indica que porcentaje estimado es anómalo (si 0.1 se espera que el 10% de datos son outliers)

In [ ]:
#15
clf = LocalOutlierFactor(n_neighbors=20, contamination=0.1)

clf

LocalOutlierFactor(contamination=0.1)

**16)** Entrena al modelo LOF y predice si cada punto es inlier o outlier.

- *fit* permite que LocalOutlierFactor aprenda la estructura de los datos.
- *predict* Después de entrenarse, devueve una predicción y la guarda en la variable *y_pred*

In [ ]:
#16
y_pred = clf.fit_predict(X)

y_pred

array([ 1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

**17)** Compara la predicción hecha vs la realidad
- Predicción: y_pred
- Realidad: ground_truth

Con .sum() suma todos los valores TRUE que es igual al número de errores del MODELO LOF.

In [ ]:
#17
n_errors = (y_pred != ground_truth).sum()

n_errors

np.int64(2)

**18)** Genera una matriz *x_scores* la cual es del mismo tamaño que la matriz *X*

- *negative_outlier_factor_* es un atributo de LOF (LocalOutlierFactor)

Asigna valores en donde si el valor es más negativo, es más probable que sea un outlier

In [ ]:
#18
X_scores = clf.negative_outlier_factor_

X_scores

220